version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: rdraw-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rdraw
    volumes:
      - mongodb_data:/data/db
    networks:
      - rdraw-network

  backend:
    build: ./backend
    container_name: rdraw-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/rdraw
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - rdraw-network

  frontend:
    build: ./frontend
    container_name: rdraw-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rdraw-network

volumes:
  mongodb_data:

networks:
  rdraw-network:
    driver: bridge